title = "CmdrX"
gitRepoUrl = "https://github.com/BiraruX/CmdrX"
gitSourceBranch = "main"
changelog = true

classOrder = [
  "CmdrX",
  "CmdrXClient",

  "Registry",
  "Dispatcher",
  "Util",

  "CommandContext",
  "ArgumentContext",
]

[docusaurus]
organizationName = "BiraruX"
projectName = "CmdrX"
url = "https://cmdrx.biraru.org"
deploymentBranch = "gh-pages"
tagline = "Extensible command console for Roblox developers. This fork was made to add small use cases that 'arent fit for production code'"
titleDelimiter = "•"
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "/logo.png"

baseUrl = "/"

# TODO: Remove when releasing new website
# noIndex = true

[home]
enabled = true
includeReadme = false

[navbar]
title = ""

[navbar.logo]
alt = "CmdrX"
src = "/name.png"

[[navbar.items]]
href = "https://github.com/BiraruX/CmdrX/releases"
label = "Releases"
position = "right"

[[navbar.items]]
href = "https://discord.gg/KTbpAEhWsf"
label = "Discord"
position = "right"

[footer]
copyright = "Made by Evaera, Modified by BiraruX. Licensed under MIT License"

[[footer.links]]
title = "Learn"
[[footer.links.items]]
label = "Introduction"
href = "/docs/intro"
[[footer.links.items]]
label = "Best practice"
href = "/docs/advanced/bestpractice"
[[footer.links.items]]
label = "API reference"
href = "/api/CmdrX"
[[footer.links.items]]
label = "Changelog"
href = "/changelog"

[[footer.links]]
title = "Community"
[[footer.links.items]]
label = "Contribute"
href = "/docs/contribute"
[[footer.links.items]]
label = "Security"
href = "/docs/community/securityreport"
[[footer.links.items]]
label = "Discord"
href = "https://discord.gg/KTbpAEhWsf"
[[footer.links.items]]
label = "Bug tracker"
href = "https://github.com/BiraruX/CmdrX/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc"
