title = "CmdrX"
gitRepoUrl = "https://github.com/BiraruStudios/CmdrX"
gitSourceBranch = "main"
changelog = true

classOrder = [
  "CmdrX",
  "CmdrXClient",

  "Registry",
  "Dispatcher",
  "Util",

  "CommandContext",
  "ArgumentContext",
]

[docusaurus]
deploymentBranch = "gh-pages"
titleDelimiter = "•"

url = "https://biraru.top"
baseUrl = "/CmdrX/"

# TODO: Remove when releasing new website
noIndex = true

[home]
enabled = true
includeReadme = false

[navbar]
title = ""

[navbar.logo]
alt = "CmdrX"
src = "/logo.png"

[[navbar.items]]
href = "https://github.com/BiraruStudios/CmdrX/releases"
label = "Releases"
position = "right"

[footer]
copyright = "Built using Docusaurus and Moonwave. Released under the <a href=\"https://github.com/BiraruStudios/CmdrX/blob/master/LICENSE\" target=\"_blank\">MIT License</a>."

[[footer.links]]
title = "Learn"
[[footer.links.items]]
label = "Introduction"
href = "/docs/intro"
[[footer.links.items]]
label = "Best practice"
href = "/docs/advanced/bestpractice"
[[footer.links.items]]
label = "API reference"
href = "/api/CmdrX"
[[footer.links.items]]
label = "Changelog"
href = "/changelog"

[[footer.links]]
title = "Community"
[[footer.links.items]]
label = "Contribute"
href = "/docs/contribute"
[[footer.links.items]]
label = "Security"
href = "/docs/community/securityreport"
[[footer.links.items]]
label = "Bug tracker"
href = "https://github.com/BiraruStudios/CmdrX/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc"
