[package]
name = "birarustudios/cmdrx"
description = "An advanced, developer-focused command console for Roblox. Built for speed, fueled by extensibility, and designed to put total game management at your fingertips."
version = "1.13.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"
exclude = ["assets", "docs"]
include = ["CHANGELOG.md", "CmdrX", "default.project.json", "LICENSE"]

[dependencies]
