[package]
name = "birarux/cmdrx"
description = "Extensible command console for Roblox developers. This fork was made to add small use cases that 'arent fit for production code'"
version = "1.13.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"
exclude = ["assets", "docs"]
include = ["CHANGELOG.md", "Cmdr", "default.project.json", "LICENSE"]

[dependencies]
